# Exploratory Data Analysis

### Importing libraries

In [157]:
#data exploration&manipulation
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from collections import Counter
import seaborn as sns

import datetime as dt
import os
import matplotlib.pyplot as plt
from scipy import stats

#ML Models search and optimisation
from pycaret.regression import * 
from sklearn.model_selection import train_test_split 
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score, confusion_matrix
import optuna
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

from catboost import CatBoostRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.tree import DecisionTreeRegressor

import pycaret
from pycaret.regression import *

### Reading and cleaning the data set

In [158]:
   
# Import space_X_train.csv
import pandas as pd
players_train = pd.read_csv(r'C:\Users\march\000 Treball Ju`yter 000\Hackathons\JOBarcelona2022\train.csv', sep=',', encoding='UTF-8')

In [159]:
players_train.head()

,Unnamed: 0,red_card_continent,age,nation,league,team,goals_selection,selections_nation,position,price,...,assist_cup,own_goal_cup,yellow_card_cup,second_yellow_card_cup,red_card_cup,goal_continent,assist_continent,own_goal_continent,yellow_card_continent,second_yellow_card_continent
0,1019,0.0,23.0,Tunisia,Ligue1,OGCNice,0.0,4.0,Goalkeeper,1000000.0,...,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0
1,1892,0.0,20.0,CzechRepublic,FortunaLiga,1.FKPribram,0.0,1.0,LeftWinger,100000.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2548,7.0,31.0,Canada,SuperLiga,RedStar,0.0,40.0,Goalkeeper,3000000.0,...,0.0,0.0,0.0,0.0,23.0,0.0,0.0,0.0,0.0,25.0
3,3137,0.0,22.0,Belgium,JupilerProLeague,ClubBrugge,4.0,18.0,SecondStriker,4000000.0,...,3.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0
4,2576,0.0,29.0,Ukraine,PremierLiga,Chornomorets,0.0,0.0,LeftMidfield,500000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [160]:
players_train.shape

(8897, 27)

In [161]:
players_train.isnull().sum()

Unnamed: 0                        0
red_card_continent              147
age                             147
nation                          147
league                          147
team                            147
goals_selection                 147
selections_nation               147
position                        147
price                           147
goal_champ                      147
assist_champ                    147
own_goal_champ                  147
yellow_card_champ               147
second_yellow_card_champ        147
red_card_champ                  147
goal_cup                        147
assist_cup                      147
own_goal_cup                    147
yellow_card_cup                 147
second_yellow_card_cup          147
red_card_cup                    147
goal_continent                  147
assist_continent                147
own_goal_continent              147
yellow_card_continent           147
second_yellow_card_continent    147
dtype: int64

In [162]:
index_null=players_train[players_train.price.isnull()].index

In [163]:
players_train.shape

(8897, 27)

In [164]:
for column in players_train.columns:
    print (f" {column} ----------->>> {players_train[column].nunique()}")

 Unnamed: 0 ----------->>> 8897
 red_card_continent ----------->>> 32
 age ----------->>> 29
 nation ----------->>> 157
 league ----------->>> 70
 team ----------->>> 1042
 goals_selection ----------->>> 37
 selections_nation ----------->>> 126
 position ----------->>> 12
 price ----------->>> 118
 goal_champ ----------->>> 133
 assist_champ ----------->>> 111
 own_goal_champ ----------->>> 6
 yellow_card_champ ----------->>> 115
 second_yellow_card_champ ----------->>> 10
 red_card_champ ----------->>> 9
 goal_cup ----------->>> 27
 assist_cup ----------->>> 22
 own_goal_cup ----------->>> 4
 yellow_card_cup ----------->>> 24
 second_yellow_card_cup ----------->>> 4
 red_card_cup ----------->>> 68
 goal_continent ----------->>> 30
 assist_continent ----------->>> 29
 own_goal_continent ----------->>> 3
 yellow_card_continent ----------->>> 26
 second_yellow_card_continent ----------->>> 72

In [165]:
players_train.columns

Index(['Unnamed: 0', 'red_card_continent', 'age', 'nation', 'league', 'team',
       'goals_selection', 'selections_nation', 'position', 'price',
       'goal_champ', 'assist_champ', 'own_goal_champ', 'yellow_card_champ',
       'second_yellow_card_champ', 'red_card_champ', 'goal_cup', 'assist_cup',
       'own_goal_cup', 'yellow_card_cup', 'second_yellow_card_cup',
       'red_card_cup', 'goal_continent', 'assist_continent',
       'own_goal_continent', 'yellow_card_continent',
       'second_yellow_card_continent'],
      dtype='object')

In [166]:
#Correct Data Frame
players_train = pd.read_csv(r'C:\Users\march\000 Treball Ju`yter 000\Hackathons\JOBarcelona2022\train.csv', sep=',', encoding='UTF-8')
list_to_arrange=[]
for i in index_null:
    player_null= players_train.iloc[i]['Unnamed: 0'].split(',')
    if len(player_null)==28:
        list_to_arrange.append(i)
             
    j=0
    for column in players_train.columns:
        if len(player_null)==28:
            player_null[4]= player_null[4] + '_'+ player_null[5]
            player_null.pop(5)
                                                
        players_train.at[i,column]= player_null[j]
        j+=1

In [167]:
players_train. rename(columns = {'Unnamed: 0':'player_ID'}, inplace = True)#Change name of column

In [168]:
#Arrange column price to be the second one
players_train[['player_ID', 'price','red_card_continent', 'age', 'nation', 'league', 'team',
       'goals_selection', 'selections_nation', 'position', 
       'goal_champ', 'assist_champ', 'own_goal_champ', 'yellow_card_champ',
       'second_yellow_card_champ', 'red_card_champ', 'goal_cup', 'assist_cup',
       'own_goal_cup', 'yellow_card_cup', 'second_yellow_card_cup',
       'red_card_cup', 'goal_continent', 'assist_continent',
       'own_goal_continent', 'yellow_card_continent',
       'second_yellow_card_continent']]

,player_ID,price,red_card_continent,age,nation,league,team,goals_selection,selections_nation,position,...,assist_cup,own_goal_cup,yellow_card_cup,second_yellow_card_cup,red_card_cup,goal_continent,assist_continent,own_goal_continent,yellow_card_continent,second_yellow_card_continent
0,1019,1000000.0,0.0,23.0,Tunisia,Ligue1,OGCNice,0.0,4.0,Goalkeeper,...,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0
1,1892,100000.0,0.0,20.0,CzechRepublic,FortunaLiga,1.FKPribram,0.0,1.0,LeftWinger,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2548,3000000.0,7.0,31.0,Canada,SuperLiga,RedStar,0.0,40.0,Goalkeeper,...,0.0,0.0,0.0,0.0,23.0,0.0,0.0,0.0,0.0,25.0
3,3137,4000000.0,0.0,22.0,Belgium,JupilerProLeague,ClubBrugge,4.0,18.0,SecondStriker,...,3.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0
4,2576,500000.0,0.0,29.0,Ukraine,PremierLiga,Chornomorets,0.0,0.0,LeftMidfield,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8892,3659,125000.0,0.0,24.0,Russia,PremierLiga,ArsenalTula,0.0,0.0,Goalkeeper,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8893,9063,300000.0,0.0,24.0,Uruguay,PrimeraDivisión,Argentinos,0.0,0.0,AttackingMidfield,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8894,9163,800000.0,0.0,29.0,Argentina,PrimeraDivisión,Defensa,0.0,11.0,Goalkeeper,...,0.0,0.0,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0
8895,2980,300000.0,0.0,29.0,Argentina,SuperLeague,ApollonSmyrnis,1.0,2.0,AttackingMidfield,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
8896,10368,175000.0,0.0,30.0,China,LeagueOne,YBFunde,0.0,0.0,LeftMidfield,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [169]:
for column in ['red_card_continent', 
               'age',
               'goals_selection', 
               'selections_nation', 
               'price',
               'goal_champ', 
               'assist_champ', 
               'own_goal_champ', 
               'yellow_card_champ',
               'second_yellow_card_champ', 
               'red_card_champ', 
               'goal_cup', 
               'assist_cup',
               'own_goal_cup', 
               'yellow_card_cup', 
               'second_yellow_card_cup',
               'red_card_cup', 
               'goal_continent', 
               'assist_continent',
               'own_goal_continent', 
               'yellow_card_continent',
               'second_yellow_card_continent']:
    players_train = players_train.astype({column: float}, errors='raise')
    players_train = players_train.astype({column: int}, errors='raise')

In [171]:
players_train.to_csv('df_players_to_graph.csv')

In [172]:
players_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8897 entries, 0 to 8896
Data columns (total 27 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   player_ID                     8897 non-null   object
 1   red_card_continent            8897 non-null   int32
 2   age                           8897 non-null   int32
 3   nation                        8897 non-null   object
 4   league                        8897 non-null   object
 5   team                          8897 non-null   object
 6   goals_selection               8897 non-null   int32
 7   selections_nation             8897 non-null   int32
 8   position                      8897 non-null   object
 9   price                         8897 non-null   int32
 10  goal_champ                    8897 non-null   int32
 11  assist_champ                  8897 non-null   int32
 12  own_goal_champ                8897 non-null   int32
 13  yellow_card_champ             8897 non-null   int32
 14  second_yellow_card_champ      8897 non-null   int32
 15  red_card_champ                8897 non-null   int32
 16  goal_cup                      8897 non-null   int32
 17  assist_cup                    8897 non-null   int32
 18  own_goal_cup                  8897 non-null   int32
 19  yellow_card_cup               8897 non-null   int32
 20  second_yellow_card_cup        8897 non-null   int32
 21  red_card_cup                  8897 non-null   int32
 22  goal_continent                8897 non-null   int32
 23  assist_continent              8897 non-null   int32
 24  own_goal_continent            8897 non-null   int32
 25  yellow_card_continent         8897 non-null   int32
 26  second_yellow_card_continent  8897 non-null   int32
dtypes: int32(22), object(5)
memory usage: 1.1+ MB

In [81]:
players_train.describe()

,Unnamed: 0,red_card_continent,age,nation,league,team,goals_selection,selections_nation,position,price,...,assist_cup,own_goal_cup,yellow_card_cup,second_yellow_card_cup,red_card_cup,goal_continent,assist_continent,own_goal_continent,yellow_card_continent,second_yellow_card_continent
count,8897,8897.0,8897.0,8897,8897,8897,8897.0,8897.0,8897,8897.0,...,8897.0,8897.0,8897.0,8897.0,8897.0,8897.0,8897.0,8897.0,8897.0,8897.0
unique,8897,39.0,48.0,158,88,1049,46.0,155.0,12,160.0,...,28.0,5.0,29.0,6.0,76.0,40.0,39.0,4.0,34.0,82.0
top,1019,0.0,25.0,Brazil,PremierLeague,TokushimaVort.,0.0,0.0,Goalkeeper,100000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
freq,1,8277.0,740.0,612,546,30,7395.0,4972.0,1701,679.0,...,6545.0,8598.0,6073.0,8500.0,7663.0,7471.0,7489.0,8683.0,7120.0,8149.0

In [120]:
players_train.groupby('position').price.mean()

position
AttackingMidfield    2.152811e+06
CentralMidfield      2.730802e+06
Defender             5.997024e+04
DefensiveMidfield    1.501792e+06
Forward              9.219512e+04
Goalkeeper           9.778777e+05
LeftMidfield         7.779180e+05
LeftWinger           2.762323e+06
Midfielder           6.906646e+04
RightMidfield        7.483498e+05
RightWinger          1.991358e+06
SecondStriker        1.723005e+06
Name: price, dtype: float64

### Visual study of data

In [173]:
import plotly.express as px

# Filter the dataframe so that it does not crash the browser
df_players_to_graph_filtered = players_train.head(1000)

# Construct the graph and style it. Further customize your graph by editing this code.
# See Plotly Documentation for help: https://plotly.com/python/plotly-express/
fig = px.bar(df_players_to_graph_filtered, x='position')
fig.update_layout(
    title='position (first 1000 rows) bar chart', 
    xaxis = dict(
        rangeslider = dict(
            visible=True, 
            thickness=0.05
        )
    ), 
    yaxis = dict(

    ), 
    barmode='group', 
    paper_bgcolor='#FFFFFF', 
    showlegend=True
)
fig.show(renderer="iframe")

In [236]:
import plotly.express as px

# Filter the dataframe so that it does not crash the browser
df_players_to_graph_filtered = players_train

# Construct the graph and style it. Further customize your graph by editing this code.
# See Plotly Documentation for help: https://plotly.com/python/plotly-express/
fig = px.box(df_players_to_graph_filtered, x='position', y='price')
fig.update_layout(
    title='position vs price in box plot', 
    xaxis = dict(
        rangeslider = dict(
            visible=True, 
            thickness=0.05
        )
    ), 
    yaxis = dict(

    ), 
    barmode='stack', 
    paper_bgcolor='#FFFFFF', 
    showlegend=True
)
fig.show(renderer="iframe")

In [237]:
### Data Engineering

In [244]:
def dummies_position_get (df):
    dummies_position=pd.get_dummies(df.position)
    new_df = pd.concat([df, dummies_position],axis=1)
    new_df.drop('position',axis=1, inplace=True)
    return new_df

def dummies_nation_get (df):
    dummies_nation=pd.get_dummies(df.nation)
    new_df = pd.concat([df, dummies_nation],axis=1)
    new_df.drop('nation',axis=1, inplace=True)
    return new_df

In [245]:
players_train_dummies_pos = dummies_position_get(players_train)
players_train_dummies_nat = dummies_nation_get(players_train)
players_train_dummies_nat_pos = dummies_nation_get(players_train_dummies_pos)

In [175]:
dummies_position=pd.get_dummies(players_train.position)
players_train_dummies = pd.concat([players_train, dummies_position],axis=1)
players_train_dummies.drop('position',axis=1, inplace=True)
players_train_dummies

,player_ID,red_card_continent,age,nation,league,team,goals_selection,selections_nation,price,goal_champ,...,Defender,DefensiveMidfield,Forward,Goalkeeper,LeftMidfield,LeftWinger,Midfielder,RightMidfield,RightWinger,SecondStriker
0,1019,0,23,Tunisia,Ligue1,OGCNice,0,4,1000000,0,...,0,0,0,1,0,0,0,0,0,0
1,1892,0,20,CzechRepublic,FortunaLiga,1.FKPribram,0,1,100000,1,...,0,0,0,0,0,1,0,0,0,0
2,2548,7,31,Canada,SuperLiga,RedStar,0,40,3000000,0,...,0,0,0,1,0,0,0,0,0,0
3,3137,0,22,Belgium,JupilerProLeague,ClubBrugge,4,18,4000000,33,...,0,0,0,0,0,0,0,0,0,1
4,2576,0,29,Ukraine,PremierLiga,Chornomorets,0,0,500000,20,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8892,3659,0,24,Russia,PremierLiga,ArsenalTula,0,0,125000,0,...,0,0,0,1,0,0,0,0,0,0
8893,9063,0,24,Uruguay,PrimeraDivisión,Argentinos,0,0,300000,12,...,0,0,0,0,0,0,0,0,0,0
8894,9163,0,29,Argentina,PrimeraDivisión,Defensa,0,11,800000,0,...,0,0,0,1,0,0,0,0,0,0
8895,2980,0,29,Argentina,SuperLeague,ApollonSmyrnis,1,2,300000,19,...,0,0,0,0,0,0,0,0,0,0
8896,10368,0,30,China,LeagueOne,YBFunde,0,0,175000,15,...,0,0,0,0,1,0,0,0,0,0

In [176]:
import plotly.express as px

# Filter the dataframe so that it does not crash the browser
df_players_to_graph_filtered = players_train.copy()

# Construct the graph and style it. Further customize your graph by editing this code.
# See Plotly Documentation for help: https://plotly.com/python/plotly-express/
fig = px.box(df_players_to_graph_filtered, x='price', y='league')
fig.update_layout(
    title='price, league (first 1000 rows) box plot', 
    xaxis = dict(
        rangeslider = dict(
            visible=True, 
            thickness=0.05
        )
    ), 
    yaxis = dict(

    ), 
    barmode='stack', 
    paper_bgcolor='#FFFFFF', 
    showlegend=True
)

fig.update_layout(
    autosize=False,
    width=850,
    height=1000,
    margin=dict(
        l=50,
        r=50,
        b=100,
        t=100,
        pad=4
    ),
    paper_bgcolor="LightSteelBlue",
)

fig.show(renderer="iframe")

In [177]:
import plotly.express as px


df_players_to_graph_filtered = players_train.copy()

# Construct the graph and style it. Further customize your graph by editing this code.
# See Plotly Documentation for help: https://plotly.com/python/plotly-express/
fig = px.box(df_players_to_graph_filtered, x='price')
fig.update_layout(
    title='price (first 1000 rows) box plot', 
    xaxis = dict(
        rangeslider = dict(
            visible=True, 
            thickness=0.05
        )
    ), 
    yaxis = dict(

    ), 
    barmode='stack', 
    paper_bgcolor='#FFFFFF', 
    showlegend=True
)
fig.show(renderer="iframe")

In [234]:
players_train.shape

(8897, 27)

In [235]:
#outliers elimination: 1st method z score:
z = np.abs(stats.zscore(players_train.price))
outliers_indice =(np.where(z < 3))[0].tolist()
players_train_no_outliers1=players_train.iloc[outliers_indice,:]
players_train_no_outliers1.shape

(8778, 27)

In [227]:
#outliers elimination: 2nd method IQR score:
cols = ['price'] # one or more columns

Q1 = players_train[cols].quantile(0.25)
Q3 = players_train[cols].quantile(0.75)
IQR = Q3 - Q1
print(IQR)

players_train_no_outliers2 = players_train[~((players_train[cols] < (Q1 - 1.5 * IQR)) |(players_train[cols] > (Q3 + 1.5 * IQR))).any(axis=1)]

700000.0

In [225]:
z = np.abs(stats.zscore(players_train.price))
outliers_indice =(np.where(z < 3))[0].tolist()
players_train_no_outliers1=players_train.iloc[outliers_indice,:]
players_train_no_outliers1.shape

(8778, 27)

In [229]:
players_train_no_outliers2.shape

(7713, 27)

## Model screening

### With outliers

With Pycaret we test the dataframe with several models to check its performance with :

In [240]:
players_train.head()

,player_ID,red_card_continent,age,nation,league,team,goals_selection,selections_nation,position,price,...,assist_cup,own_goal_cup,yellow_card_cup,second_yellow_card_cup,red_card_cup,goal_continent,assist_continent,own_goal_continent,yellow_card_continent,second_yellow_card_continent
0,1019,0,23,Tunisia,Ligue1,OGCNice,0,4,Goalkeeper,1000000,...,0,0,0,0,12,0,0,0,0,0
1,1892,0,20,CzechRepublic,FortunaLiga,1.FKPribram,0,1,LeftWinger,100000,...,0,0,1,0,0,0,0,0,0,0
2,2548,7,31,Canada,SuperLiga,RedStar,0,40,Goalkeeper,3000000,...,0,0,0,0,23,0,0,0,0,25
3,3137,0,22,Belgium,JupilerProLeague,ClubBrugge,4,18,SecondStriker,4000000,...,3,0,2,0,0,0,1,0,2,0
4,2576,0,29,Ukraine,PremierLiga,Chornomorets,0,0,LeftMidfield,500000,...,0,0,0,0,0,0,0,0,0,0

In [75]:
reg = setup(data = players_train, target = 'price')

In [76]:
best_model=compare_models()

### Without outliers (removed by z score)

In [239]:
players_train_no_outliers1.head()

,player_ID,red_card_continent,age,nation,league,team,goals_selection,selections_nation,position,price,...,assist_cup,own_goal_cup,yellow_card_cup,second_yellow_card_cup,red_card_cup,goal_continent,assist_continent,own_goal_continent,yellow_card_continent,second_yellow_card_continent
0,1019,0,23,Tunisia,Ligue1,OGCNice,0,4,Goalkeeper,1000000,...,0,0,0,0,12,0,0,0,0,0
1,1892,0,20,CzechRepublic,FortunaLiga,1.FKPribram,0,1,LeftWinger,100000,...,0,0,1,0,0,0,0,0,0,0
2,2548,7,31,Canada,SuperLiga,RedStar,0,40,Goalkeeper,3000000,...,0,0,0,0,23,0,0,0,0,25
3,3137,0,22,Belgium,JupilerProLeague,ClubBrugge,4,18,SecondStriker,4000000,...,3,0,2,0,0,0,1,0,2,0
4,2576,0,29,Ukraine,PremierLiga,Chornomorets,0,0,LeftMidfield,500000,...,0,0,0,0,0,0,0,0,0,0

In [230]:
reg2 = setup(data = players_train_no_outliers1, target = 'price')

In [231]:
best_model2=compare_models()

References:
    *Pycaret for regression :
    https://insaid.medium.com/regression-in-pycaret-c034bf442416

### Without outliers (removed by IQR score)

In [238]:
players_train_no_outliers2.head()

,player_ID,red_card_continent,age,nation,league,team,goals_selection,selections_nation,position,price,...,assist_cup,own_goal_cup,yellow_card_cup,second_yellow_card_cup,red_card_cup,goal_continent,assist_continent,own_goal_continent,yellow_card_continent,second_yellow_card_continent
0,1019,0,23,Tunisia,Ligue1,OGCNice,0,4,Goalkeeper,1000000,...,0,0,0,0,12,0,0,0,0,0
1,1892,0,20,CzechRepublic,FortunaLiga,1.FKPribram,0,1,LeftWinger,100000,...,0,0,1,0,0,0,0,0,0,0
4,2576,0,29,Ukraine,PremierLiga,Chornomorets,0,0,LeftMidfield,500000,...,0,0,0,0,0,0,0,0,0,0
5,12125,0,25,Japan,J1League,MatsumotoYama.,0,0,LeftMidfield,200000,...,0,0,0,0,0,0,0,0,0,0
7,11233,0,32,Iran,PersianGulfProLeague,ParsJam,0,0,RightWinger,100000,...,1,0,1,0,1,0,0,0,0,0

In [232]:
reg3 = setup(data = players_train_no_outliers2, target = 'price')

In [233]:
best_model3=compare_models()

In [ ]:
### With utliers and dummies for nation and position

In [248]:
players_train_dummies_nat_pos.head()

,player_ID,red_card_continent,age,league,team,goals_selection,selections_nation,price,goal_champ,assist_champ,...,UnitedStates,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam,Wales,Yemen,Zambia,Zimbabwe
0,1019,0,23,Ligue1,OGCNice,0,4,1000000,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1892,0,20,FortunaLiga,1.FKPribram,0,1,100000,1,1,...,0,0,0,0,0,0,0,0,0,0
2,2548,7,31,SuperLiga,RedStar,0,40,3000000,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3137,0,22,JupilerProLeague,ClubBrugge,4,18,4000000,33,22,...,0,0,0,0,0,0,0,0,0,0
4,2576,0,29,PremierLiga,Chornomorets,0,0,500000,20,19,...,0,0,0,0,0,0,0,0,0,0

In [246]:
reg4 = setup(data = players_train_dummies_nat_pos, target = 'price')ç

In [247]:
best_model4=compare_models()

## Model optimization

References:
  * Optuna for regression :
        https://www.kaggle.com/code/pourchot/tuning-regression-with-optuna-for-cat-lgb-xgb/notebook

In [151]:
import numpy as np
import pandas as pd
import lightgbm as lgb
import xgboost as xgb
from catboost import CatBoostRegressor

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

### CatBoostRegressor with Optuna

In [281]:
columns_feat= list(players_train_dummies_nat_pos.columns)
columns_feat.pop(0)
columns_feat.pop(6)
columns_feat.pop(3)
columns_feat.pop(2)
FEATURES= columns_feat

In [289]:
train=players_train_dummies_nat_pos.copy()
train.drop(['player_ID','team','league'], axis = 1, inplace = True)
target=players_train_dummies_nat_pos['price']
TARGET='price'
players_train_dummies_nat_pos.head()

,player_ID,red_card_continent,age,league,team,goals_selection,selections_nation,price,goal_champ,assist_champ,...,UnitedStates,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam,Wales,Yemen,Zambia,Zimbabwe
0,1019,0,23,Ligue1,OGCNice,0,4,1000000,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1892,0,20,FortunaLiga,1.FKPribram,0,1,100000,1,1,...,0,0,0,0,0,0,0,0,0,0
2,2548,7,31,SuperLiga,RedStar,0,40,3000000,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3137,0,22,JupilerProLeague,ClubBrugge,4,18,4000000,33,22,...,0,0,0,0,0,0,0,0,0,0
4,2576,0,29,PremierLiga,Chornomorets,0,0,500000,20,19,...,0,0,0,0,0,0,0,0,0,0

In [290]:
N_split = 2
kf = KFold(n_splits=N_split)

def objective(trial):
    params = {
                #'iterations' : 10000, replaced by early stopping
                'eval_metric': 'SMAPE', 
                'use_best_model': True,
                'random_seed' : 1,
                'learning_rate' :trial.suggest_loguniform('learning_rate', 0.01, 0.3),
                "depth": trial.suggest_int("depth", 1, 15),
                'l2_leaf_reg' :trial.suggest_loguniform('l2_leaf_reg', 1e-8, 20),
                'random_strength' : trial.suggest_loguniform('random_strength', 1, 50),
                'grow_policy':trial.suggest_categorical ('grow_policy', ['Lossguide','SymmetricTree']),
                'max_bin': trial.suggest_int("max_bin", 20, 500),
                'min_data_in_leaf':trial.suggest_int('min_data_in_leaf', 1, 100),
                "bootstrap_type": trial.suggest_categorical("bootstrap_type", ["Bayesian", "Bernoulli"])
            }
    
    if params['grow_policy'] == 'Lossguide':
        params['max_leaves']:trial.suggest_int('max_leaves', 1, 100)
    if params["bootstrap_type"] == "Bayesian":
        params["bagging_temperature"] = trial.suggest_float("bagging_temperature", 0, 10)
    elif params["bootstrap_type"] == "Bernoulli":
        params["subsample"] = trial.suggest_float("subsample", 0.1, 1)
        
    
    score_list = []
    
    for fold, (train_idx, val_idx) in enumerate(kf.split(train, train[TARGET])):
        X_tr = train.loc[train_idx][FEATURES]
        X_va = train.iloc[val_idx][FEATURES]
        
        # Preprocess the data
        X_tr_f = X_tr # Use the correct preprocessing if required (normalization...)
        y_tr = train[TARGET].loc[train_idx].values

        X_va_f = X_va # Use the correct preprocessing if required (normalization...)
        y_va = train[TARGET].loc[val_idx].values

        # Train the model
        model = CatBoostRegressor(**params) 
        model.fit(        
                X_tr_f,
                y_tr,
                eval_set =[( X_va_f,y_va)],
                verbose =0,
                early_stopping_rounds = 200)

        # Predictions
        y_va_pred = model.predict(X_va_f)
        score = mean_squared_error(y_va, y_va_pred,squared = True)
        score_list.append(score)
        
    return sum(score_list) / len(score_list)

study4 = optuna.create_study(direction='minimize')
study4.optimize(objective, n_trials=20)

[I 2022-05-31 00:18:26,953] A new study created in memory with name: no-name-c6f0e437-1299-42b9-a8c4-5c874be02b4f
[I 2022-05-31 00:18:57,349] Trial 0 finished with value: 28697971745376.9 and parameters: {'learning_rate': 0.24065647198080262, 'depth': 9, 'l2_leaf_reg': 3.845519829192643e-05, 'random_strength': 17.27976337150255, 'grow_policy': 'SymmetricTree', 'max_bin': 314, 'min_data_in_leaf': 47, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 5.195366155929846}. Best is trial 0 with value: 28697971745376.9.
[I 2022-05-31 00:19:11,210] Trial 1 finished with value: 27953028211975.875 and parameters: {'learning_rate': 0.011989327103275684, 'depth': 6, 'l2_leaf_reg': 3.7032538624774304e-06, 'random_strength': 6.6421226810337, 'grow_policy': 'Lossguide', 'max_bin': 288, 'min_data_in_leaf': 37, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 1.0820569106082234}. Best is trial 1 with value: 27953028211975.875.
[I 2022-05-31 00:19:17,071] Trial 2 finished with value: 34524307433761.473 and parameters: {'learning_rate': 0.06843309623307361, 'depth': 13, 'l2_leaf_reg': 0.2182864639984827, 'random_strength': 37.294422656897744, 'grow_policy': 'Lossguide', 'max_bin': 452, 'min_data_in_leaf': 69, 'bootstrap_type': 'Bernoulli', 'subsample': 0.4134835753659054}. Best is trial 1 with value: 27953028211975.875.
[I 2022-05-31 00:19:19,442] Trial 3 finished with value: 31798154249755.793 and parameters: {'learning_rate': 0.1606073855850012, 'depth': 2, 'l2_leaf_reg': 4.911977108921085, 'random_strength': 2.423747365950277, 'grow_policy': 'Lossguide', 'max_bin': 302, 'min_data_in_leaf': 42, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 6.641928144764673}. Best is trial 1 with value: 27953028211975.875.
[I 2022-05-31 00:19:21,882] Trial 4 finished with value: 33917071880764.586 and parameters: {'learning_rate': 0.15988174951925743, 'depth': 4, 'l2_leaf_reg': 1.4069302273561625e-05, 'random_strength': 30.36398291228312, 'grow_policy': 'Lossguide', 'max_bin': 253, 'min_data_in_leaf': 95, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 1.3668350155988396}. Best is trial 1 with value: 27953028211975.875.
[I 2022-05-31 00:22:17,577] Trial 5 finished with value: 27864268935206.742 and parameters: {'learning_rate': 0.059811331358054574, 'depth': 12, 'l2_leaf_reg': 0.0019471896042734097, 'random_strength': 1.4106641215293458, 'grow_policy': 'SymmetricTree', 'max_bin': 387, 'min_data_in_leaf': 53, 'bootstrap_type': 'Bernoulli', 'subsample': 0.9601847333455185}. Best is trial 5 with value: 27864268935206.742.
[I 2022-05-31 00:22:25,716] Trial 6 finished with value: 30687150611724.777 and parameters: {'learning_rate': 0.12218281781243877, 'depth': 10, 'l2_leaf_reg': 6.964673059645989, 'random_strength': 4.7702494665080275, 'grow_policy': 'Lossguide', 'max_bin': 160, 'min_data_in_leaf': 41, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 8.61247298750671}. Best is trial 5 with value: 27864268935206.742.
[I 2022-05-31 00:23:11,033] Trial 7 finished with value: 30377239138889.42 and parameters: {'learning_rate': 0.027028295124856, 'depth': 11, 'l2_leaf_reg': 12.517641284118914, 'random_strength': 1.9606766210469604, 'grow_policy': 'SymmetricTree', 'max_bin': 498, 'min_data_in_leaf': 34, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 8.371076231979156}. Best is trial 5 with value: 27864268935206.742.
[I 2022-05-31 00:23:24,406] Trial 8 finished with value: 27992782433337.945 and parameters: {'learning_rate': 0.02833875995011244, 'depth': 8, 'l2_leaf_reg': 0.01986571624984388, 'random_strength': 5.844855598627235, 'grow_policy': 'Lossguide', 'max_bin': 135, 'min_data_in_leaf': 62, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 6.212347408096484}. Best is trial 5 with value: 27864268935206.742.
[I 2022-05-31 00:24:30,759] Trial 9 finished with value: 27149506794676.312 and parameters: {'learning_rate': 0.01889253680762329, 'depth': 11, 'l2_leaf_reg': 8.463566847131513e-06, 'random_strength': 1.9116889950317173, 'grow_policy': 'SymmetricTree', 'max_bin': 52, 'min_data_in_leaf': 35, 'bootstrap_type': 'Bernoulli', 'subsample': 0.3932122063508482}. Best is trial 9 with value: 27149506794676.312.
[I 2022-05-31 00:31:56,488] Trial 10 finished with value: 29416583356709.055 and parameters: {'learning_rate': 0.010270862548950578, 'depth': 14, 'l2_leaf_reg': 2.553856308452095e-08, 'random_strength': 1.1194906775511806, 'grow_policy': 'SymmetricTree', 'max_bin': 24, 'min_data_in_leaf': 4, 'bootstrap_type': 'Bernoulli', 'subsample': 0.13822468889487705}. Best is trial 9 with value: 27149506794676.312.
[I 2022-05-31 06:51:51,589] Trial 11 finished with value: 31203558285906.11 and parameters: {'learning_rate': 0.03906350647218853, 'depth': 15, 'l2_leaf_reg': 0.0010360271982742995, 'random_strength': 1.195085197892063, 'grow_policy': 'SymmetricTree', 'max_bin': 388, 'min_data_in_leaf': 18, 'bootstrap_type': 'Bernoulli', 'subsample': 0.9884254001585705}. Best is trial 9 with value: 27149506794676.312.
[I 2022-05-31 06:53:58,303] Trial 12 finished with value: 27897436990363.4 and parameters: {'learning_rate': 0.0677662900103185, 'depth': 12, 'l2_leaf_reg': 3.9856144468088864e-07, 'random_strength': 2.847930111037965, 'grow_policy': 'SymmetricTree', 'max_bin': 27, 'min_data_in_leaf': 72, 'bootstrap_type': 'Bernoulli', 'subsample': 0.9427960011431323}. Best is trial 9 with value: 27149506794676.312.
[I 2022-05-31 06:54:11,103] Trial 13 finished with value: 25697659542871.043 and parameters: {'learning_rate': 0.017320624632550977, 'depth': 7, 'l2_leaf_reg': 0.00027393238511028633, 'random_strength': 12.568105862938237, 'grow_policy': 'SymmetricTree', 'max_bin': 183, 'min_data_in_leaf': 20, 'bootstrap_type': 'Bernoulli', 'subsample': 0.5664324435891066}. Best is trial 13 with value: 25697659542871.043.
[I 2022-05-31 06:54:21,598] Trial 14 finished with value: 27532823139231.63 and parameters: {'learning_rate': 0.018248763331278353, 'depth': 7, 'l2_leaf_reg': 0.00013975010243287835, 'random_strength': 14.554551444732924, 'grow_policy': 'SymmetricTree', 'max_bin': 123, 'min_data_in_leaf': 19, 'bootstrap_type': 'Bernoulli', 'subsample': 0.5093525119981404}. Best is trial 13 with value: 25697659542871.043.
[I 2022-05-31 06:54:29,127] Trial 15 finished with value: 27662858431933.72 and parameters: {'learning_rate': 0.0171745481963418, 'depth': 6, 'l2_leaf_reg': 5.733680463699323e-07, 'random_strength': 11.871665265506255, 'grow_policy': 'SymmetricTree', 'max_bin': 213, 'min_data_in_leaf': 22, 'bootstrap_type': 'Bernoulli', 'subsample': 0.6564836017578917}. Best is trial 13 with value: 25697659542871.043.
[I 2022-05-31 06:54:33,743] Trial 16 finished with value: 28357228488318.727 and parameters: {'learning_rate': 0.018259745873966247, 'depth': 4, 'l2_leaf_reg': 0.016128277170313045, 'random_strength': 9.0904432199076, 'grow_policy': 'SymmetricTree', 'max_bin': 95, 'min_data_in_leaf': 1, 'bootstrap_type': 'Bernoulli', 'subsample': 0.3240295137752563}. Best is trial 13 with value: 25697659542871.043.
[I 2022-05-31 06:54:58,466] Trial 17 finished with value: 25815645772302.14 and parameters: {'learning_rate': 0.03427739971257556, 'depth': 9, 'l2_leaf_reg': 1.9938031115934104e-08, 'random_strength': 4.0996670548425085, 'grow_policy': 'SymmetricTree', 'max_bin': 84, 'min_data_in_leaf': 24, 'bootstrap_type': 'Bernoulli', 'subsample': 0.6653242808667021}. Best is trial 13 with value: 25697659542871.043.
[I 2022-05-31 06:54:59,994] Trial 18 finished with value: 35172144870712.953 and parameters: {'learning_rate': 0.03994736976497342, 'depth': 1, 'l2_leaf_reg': 1.3760682816558961e-08, 'random_strength': 4.008490424293864, 'grow_policy': 'SymmetricTree', 'max_bin': 193, 'min_data_in_leaf': 10, 'bootstrap_type': 'Bernoulli', 'subsample': 0.7121833000625205}. Best is trial 13 with value: 25697659542871.043.
[I 2022-05-31 06:55:06,128] Trial 19 finished with value: 25442968112105.83 and parameters: {'learning_rate': 0.0292240686840403, 'depth': 4, 'l2_leaf_reg': 3.2261267198470767e-07, 'random_strength': 23.09049916294969, 'grow_policy': 'SymmetricTree', 'max_bin': 89, 'min_data_in_leaf': 29, 'bootstrap_type': 'Bernoulli', 'subsample': 0.7469653757351812}. Best is trial 19 with value: 25442968112105.83.

In [291]:

print('Number of finished trials:', len(study3.trials))
print('Best trial:', study3.best_trial.params)

Number of finished trials: 1

ValueError: No trials are completed yet.

In [ ]:
optoptuna.visualization.plot_param_importances(study4)

In [ ]:
def evaluate_Regression_models(model_name, model,x_test,y_test):
    prediction = model.predict(x_test)
    
    MAE=mean_absolute_error(y_test,prediction)
    MSE =  np.sqrt(mean_squared_error(y_test,prediction))
    r2 = r2_score(y_test,prediction)
                                  
    print(f"Mean Absolute Error: {MAE}")
    print(f"Mean Squared Error : {MSE}") 
    print(f"r2 : {r2}")
          
    df=pd.DataFrame({"Model":model_name, "MAE":MAE, "MSE":MSE, "r2":r2})
                                 
    return df

In [348]:
def scoring_f1(y_test,X_test,method): #generation of f1 macro
    f1score=f1_score(y_test,
                     method.predict(X_test),
                     average= 'macro'
)        
    return f1score

In [12]:
import optuna

In [30]:
X=space_X_train.copy()
y=X.target
X.drop('target',axis=1, inplace=True)

In [37]:
def objective(trial):
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
    
    bootstrap = trial.suggest_categorical('bootstrap',['True','False'])
    max_depth = trial.suggest_int('max_depth', 1, 10000)
    max_features = trial.suggest_categorical('max_features', ['auto', 'sqrt','log2'])
    max_leaf_nodes = trial.suggest_int('max_leaf_nodes', 1, 10000)
    n_estimators =  trial.suggest_int('n_estimators', 30, 1000)
    
    rf_cl = RandomForestClassifier(bootstrap = bootstrap, 
                                   max_depth = max_depth, 
                                   max_features = max_features,
                                   max_leaf_nodes = max_leaf_nodes,
                                   n_estimators = n_estimators,
                                   n_jobs=2
                                  )
    
    rf_cl.fit(X_train, y_train)
    y_pred = rf_cl.predict(X_test)
    
    score = cross_val_score(rf_cl, X_test, y_test, cv=5, scoring="f1_macro")
    f1_mean = score.mean()

    return f1_mean

In [ ]:
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

[I 2022-05-29 14:01:06,267] A new study created in memory with name: no-name-9176f93c-7501-44c8-803a-a1936689613d
[I 2022-05-29 14:01:08,667] Trial 0 finished with value: 0.7078393734730708 and parameters: {'bootstrap': 'True', 'max_depth': 3375, 'max_features': 'log2', 'max_leaf_nodes': 76, 'n_estimators': 147}. Best is trial 0 with value: 0.7078393734730708.
[I 2022-05-29 14:01:18,310] Trial 1 finished with value: 0.703520960653047 and parameters: {'bootstrap': 'True', 'max_depth': 2556, 'max_features': 'log2', 'max_leaf_nodes': 8369, 'n_estimators': 629}. Best is trial 0 with value: 0.7078393734730708.
[I 2022-05-29 14:01:22,630] Trial 2 finished with value: 0.7086595236675942 and parameters: {'bootstrap': 'False', 'max_depth': 4934, 'max_features': 'log2', 'max_leaf_nodes': 2239, 'n_estimators': 254}. Best is trial 2 with value: 0.7086595236675942.
[I 2022-05-29 14:01:32,052] Trial 3 finished with value: 0.7082046285636155 and parameters: {'bootstrap': 'True', 'max_depth': 1275, 'max_features': 'log2', 'max_leaf_nodes': 110, 'n_estimators': 695}. Best is trial 2 with value: 0.7086595236675942.
[I 2022-05-29 14:01:46,947] Trial 4 finished with value: 0.7127760178589323 and parameters: {'bootstrap': 'False', 'max_depth': 9121, 'max_features': 'sqrt', 'max_leaf_nodes': 1162, 'n_estimators': 982}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:01:51,743] Trial 5 finished with value: 0.7064401294262447 and parameters: {'bootstrap': 'True', 'max_depth': 4700, 'max_features': 'log2', 'max_leaf_nodes': 3511, 'n_estimators': 290}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:01:54,738] Trial 6 finished with value: 0.7007428712166258 and parameters: {'bootstrap': 'False', 'max_depth': 297, 'max_features': 'auto', 'max_leaf_nodes': 945, 'n_estimators': 193}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:02:03,055] Trial 7 finished with value: 0.6985138205928827 and parameters: {'bootstrap': 'False', 'max_depth': 1631, 'max_features': 'sqrt', 'max_leaf_nodes': 5624, 'n_estimators': 575}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:02:12,266] Trial 8 finished with value: 0.700423964091599 and parameters: {'bootstrap': 'True', 'max_depth': 5502, 'max_features': 'log2', 'max_leaf_nodes': 6753, 'n_estimators': 596}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:02:25,165] Trial 9 finished with value: 0.6965585148853158 and parameters: {'bootstrap': 'True', 'max_depth': 9336, 'max_features': 'log2', 'max_leaf_nodes': 1488, 'n_estimators': 839}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:02:40,127] Trial 10 finished with value: 0.7105852595000481 and parameters: {'bootstrap': 'False', 'max_depth': 9871, 'max_features': 'sqrt', 'max_leaf_nodes': 3854, 'n_estimators': 960}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:02:54,128] Trial 11 finished with value: 0.7029902881885801 and parameters: {'bootstrap': 'False', 'max_depth': 9206, 'max_features': 'sqrt', 'max_leaf_nodes': 4020, 'n_estimators': 971}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:03:08,900] Trial 12 finished with value: 0.7059276512793655 and parameters: {'bootstrap': 'False', 'max_depth': 7731, 'max_features': 'sqrt', 'max_leaf_nodes': 2928, 'n_estimators': 965}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:03:21,382] Trial 13 finished with value: 0.7073624889577583 and parameters: {'bootstrap': 'False', 'max_depth': 7564, 'max_features': 'sqrt', 'max_leaf_nodes': 4946, 'n_estimators': 813}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:03:28,497] Trial 14 finished with value: 0.7014916151317492 and parameters: {'bootstrap': 'False', 'max_depth': 7501, 'max_features': 'sqrt', 'max_leaf_nodes': 7463, 'n_estimators': 435}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:03:40,653] Trial 15 finished with value: 0.7091463082446943 and parameters: {'bootstrap': 'False', 'max_depth': 9710, 'max_features': 'auto', 'max_leaf_nodes': 9360, 'n_estimators': 811}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:03:55,472] Trial 16 finished with value: 0.7085116091415277 and parameters: {'bootstrap': 'False', 'max_depth': 8383, 'max_features': 'sqrt', 'max_leaf_nodes': 5021, 'n_estimators': 991}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:04:02,095] Trial 17 finished with value: 0.7030603347246112 and parameters: {'bootstrap': 'False', 'max_depth': 6278, 'max_features': 'sqrt', 'max_leaf_nodes': 2080, 'n_estimators': 410}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:04:12,576] Trial 18 finished with value: 0.7093827803871828 and parameters: {'bootstrap': 'False', 'max_depth': 6486, 'max_features': 'sqrt', 'max_leaf_nodes': 4035, 'n_estimators': 719}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:04:26,232] Trial 19 finished with value: 0.7028016403335308 and parameters: {'bootstrap': 'False', 'max_depth': 8615, 'max_features': 'auto', 'max_leaf_nodes': 2889, 'n_estimators': 895}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:04:27,203] Trial 20 finished with value: 0.6865058590626593 and parameters: {'bootstrap': 'False', 'max_depth': 9984, 'max_features': 'sqrt', 'max_leaf_nodes': 6093, 'n_estimators': 51}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:04:38,516] Trial 21 finished with value: 0.7016233322488339 and parameters: {'bootstrap': 'False', 'max_depth': 6609, 'max_features': 'sqrt', 'max_leaf_nodes': 4363, 'n_estimators': 735}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:04:52,541] Trial 22 finished with value: 0.69974660961219 and parameters: {'bootstrap': 'False', 'max_depth': 6781, 'max_features': 'sqrt', 'max_leaf_nodes': 3359, 'n_estimators': 885}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:05:14,345] Trial 23 finished with value: 0.7102930333755474 and parameters: {'bootstrap': 'False', 'max_depth': 8620, 'max_features': 'sqrt', 'max_leaf_nodes': 1573, 'n_estimators': 719}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:05:29,815] Trial 24 finished with value: 0.6984335316761385 and parameters: {'bootstrap': 'False', 'max_depth': 8539, 'max_features': 'sqrt', 'max_leaf_nodes': 1030, 'n_estimators': 891}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:05:43,087] Trial 25 finished with value: 0.7021803968887039 and parameters: {'bootstrap': 'False', 'max_depth': 9155, 'max_features': 'sqrt', 'max_leaf_nodes': 2035, 'n_estimators': 761}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:05:51,727] Trial 26 finished with value: 0.7073198689162713 and parameters: {'bootstrap': 'False', 'max_depth': 8052, 'max_features': 'auto', 'max_leaf_nodes': 1086, 'n_estimators': 477}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:06:11,882] Trial 27 finished with value: 0.704783891972484 and parameters: {'bootstrap': 'False', 'max_depth': 9942, 'max_features': 'sqrt', 'max_leaf_nodes': 2276, 'n_estimators': 924}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:06:28,187] Trial 28 finished with value: 0.708805882824429 and parameters: {'bootstrap': 'False', 'max_depth': 3879, 'max_features': 'sqrt', 'max_leaf_nodes': 565, 'n_estimators': 1000}. Best is trial 4 with value: 0.7127760178589323.
[I 2022-05-29 14:06:39,912] Trial 29 finished with value: 0.7168913179479336 and parameters: {'bootstrap': 'True', 'max_depth': 9028, 'max_features': 'sqrt', 'max_leaf_nodes': 1652, 'n_estimators': 674}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:06:45,293] Trial 30 finished with value: 0.7114771761125769 and parameters: {'bootstrap': 'True', 'max_depth': 7185, 'max_features': 'auto', 'max_leaf_nodes': 153, 'n_estimators': 370}. Best is trial 29 with value: 0.7168913179479336.

[I 2022-05-29 14:06:50,076] Trial 31 finished with value: 0.6901402050446789 and parameters: {'bootstrap': 'True', 'max_depth': 7265, 'max_features': 'auto', 'max_leaf_nodes': 65, 'n_estimators': 363}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:06:56,194] Trial 32 finished with value: 0.7139816630356002 and parameters: {'bootstrap': 'True', 'max_depth': 8972, 'max_features': 'auto', 'max_leaf_nodes': 500, 'n_estimators': 336}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:07:04,198] Trial 33 finished with value: 0.6985651304520185 and parameters: {'bootstrap': 'True', 'max_depth': 9005, 'max_features': 'auto', 'max_leaf_nodes': 552, 'n_estimators': 527}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:07:09,160] Trial 34 finished with value: 0.6947186329314569 and parameters: {'bootstrap': 'True', 'max_depth': 5874, 'max_features': 'auto', 'max_leaf_nodes': 47, 'n_estimators': 316}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:07:19,271] Trial 35 finished with value: 0.6978783935316522 and parameters: {'bootstrap': 'True', 'max_depth': 8089, 'max_features': 'auto', 'max_leaf_nodes': 1342, 'n_estimators': 653}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:07:23,577] Trial 36 finished with value: 0.6952837815241333 and parameters: {'bootstrap': 'True', 'max_depth': 6929, 'max_features': 'auto', 'max_leaf_nodes': 2539, 'n_estimators': 225}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:07:27,224] Trial 37 finished with value: 0.6996649368566752 and parameters: {'bootstrap': 'True', 'max_depth': 3093, 'max_features': 'auto', 'max_leaf_nodes': 595, 'n_estimators': 162}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:07:35,797] Trial 38 finished with value: 0.6985421114706024 and parameters: {'bootstrap': 'True', 'max_depth': 4082, 'max_features': 'auto', 'max_leaf_nodes': 1610, 'n_estimators': 332}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:07:40,059] Trial 39 finished with value: 0.6948970288176166 and parameters: {'bootstrap': 'True', 'max_depth': 5399, 'max_features': 'log2', 'max_leaf_nodes': 542, 'n_estimators': 267}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:07:49,000] Trial 40 finished with value: 0.704581969246471 and parameters: {'bootstrap': 'True', 'max_depth': 8909, 'max_features': 'auto', 'max_leaf_nodes': 1797, 'n_estimators': 551}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:07:55,220] Trial 41 finished with value: 0.71112026788006 and parameters: {'bootstrap': 'True', 'max_depth': 9493, 'max_features': 'log2', 'max_leaf_nodes': 778, 'n_estimators': 401}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:08:02,431] Trial 42 finished with value: 0.7053686382950605 and parameters: {'bootstrap': 'True', 'max_depth': 9380, 'max_features': 'log2', 'max_leaf_nodes': 868, 'n_estimators': 397}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:08:09,217] Trial 43 finished with value: 0.7108897236614464 and parameters: {'bootstrap': 'True', 'max_depth': 8001, 'max_features': 'log2', 'max_leaf_nodes': 360, 'n_estimators': 482}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:08:18,098] Trial 44 finished with value: 0.7082739074718918 and parameters: {'bootstrap': 'True', 'max_depth': 9395, 'max_features': 'log2', 'max_leaf_nodes': 1258, 'n_estimators': 610}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:08:24,623] Trial 45 finished with value: 0.6949110700490898 and parameters: {'bootstrap': 'True', 'max_depth': 9486, 'max_features': 'log2', 'max_leaf_nodes': 996, 'n_estimators': 474}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:08:29,776] Trial 46 finished with value: 0.7133478262372109 and parameters: {'bootstrap': 'True', 'max_depth': 7167, 'max_features': 'log2', 'max_leaf_nodes': 2567, 'n_estimators': 369}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:08:42,466] Trial 47 finished with value: 0.7017016594222836 and parameters: {'bootstrap': 'True', 'max_depth': 7378, 'max_features': 'auto', 'max_leaf_nodes': 2938, 'n_estimators': 661}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:08:47,147] Trial 48 finished with value: 0.7080605043091727 and parameters: {'bootstrap': 'True', 'max_depth': 7102, 'max_features': 'log2', 'max_leaf_nodes': 2333, 'n_estimators': 241}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:08:54,666] Trial 49 finished with value: 0.6985104210443688 and parameters: {'bootstrap': 'True', 'max_depth': 6039, 'max_features': 'auto', 'max_leaf_nodes': 2654, 'n_estimators': 352}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:08:59,363] Trial 50 finished with value: 0.7149449601405969 and parameters: {'bootstrap': 'True', 'max_depth': 4747, 'max_features': 'log2', 'max_leaf_nodes': 3364, 'n_estimators': 296}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:09:01,471] Trial 51 finished with value: 0.694128580033215 and parameters: {'bootstrap': 'True', 'max_depth': 4855, 'max_features': 'log2', 'max_leaf_nodes': 3329, 'n_estimators': 107}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:09:06,606] Trial 52 finished with value: 0.7118216065283984 and parameters: {'bootstrap': 'True', 'max_depth': 4341, 'max_features': 'log2', 'max_leaf_nodes': 1901, 'n_estimators': 296}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:09:11,145] Trial 53 finished with value: 0.6999299157475323 and parameters: {'bootstrap': 'True', 'max_depth': 4395, 'max_features': 'log2', 'max_leaf_nodes': 3700, 'n_estimators': 295}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:09:13,845] Trial 54 finished with value: 0.7082501198110759 and parameters: {'bootstrap': 'True', 'max_depth': 2447, 'max_features': 'log2', 'max_leaf_nodes': 1876, 'n_estimators': 186}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:09:18,255] Trial 55 finished with value: 0.7082974802884874 and parameters: {'bootstrap': 'True', 'max_depth': 5241, 'max_features': 'log2', 'max_leaf_nodes': 4566, 'n_estimators': 291}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:09:20,524] Trial 56 finished with value: 0.6934400821398474 and parameters: {'bootstrap': 'True', 'max_depth': 3958, 'max_features': 'log2', 'max_leaf_nodes': 2947, 'n_estimators': 116}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:09:26,961] Trial 57 finished with value: 0.7053242605601778 and parameters: {'bootstrap': 'True', 'max_depth': 3576, 'max_features': 'log2', 'max_leaf_nodes': 3276, 'n_estimators': 435}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:09:30,011] Trial 58 finished with value: 0.6971074870520972 and parameters: {'bootstrap': 'True', 'max_depth': 5766, 'max_features': 'log2', 'max_leaf_nodes': 1544, 'n_estimators': 206}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:09:34,884] Trial 59 finished with value: 0.7028409856418452 and parameters: {'bootstrap': 'True', 'max_depth': 4576, 'max_features': 'sqrt', 'max_leaf_nodes': 9539, 'n_estimators': 326}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:09:39,005] Trial 60 finished with value: 0.7137370904881607 and parameters: {'bootstrap': 'True', 'max_depth': 5092, 'max_features': 'log2', 'max_leaf_nodes': 2016, 'n_estimators': 256}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:09:43,361] Trial 61 finished with value: 0.7116481623323129 and parameters: {'bootstrap': 'True', 'max_depth': 5116, 'max_features': 'log2', 'max_leaf_nodes': 2216, 'n_estimators': 270}. Best is trial 29 with value: 0.7168913179479336.

[I 2022-05-29 14:09:47,105] Trial 62 finished with value: 0.7047831314263585 and parameters: {'bootstrap': 'True', 'max_depth': 2940, 'max_features': 'log2', 'max_leaf_nodes': 2664, 'n_estimators': 246}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:10:00,284] Trial 63 finished with value: 0.7045335612437575 and parameters: {'bootstrap': 'True', 'max_depth': 278, 'max_features': 'log2', 'max_leaf_nodes': 1847, 'n_estimators': 850}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:10:06,947] Trial 64 finished with value: 0.6966919262218025 and parameters: {'bootstrap': 'True', 'max_depth': 1658, 'max_features': 'sqrt', 'max_leaf_nodes': 7802, 'n_estimators': 430}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:10:12,956] Trial 65 finished with value: 0.7029610018728795 and parameters: {'bootstrap': 'True', 'max_depth': 8833, 'max_features': 'log2', 'max_leaf_nodes': 1464, 'n_estimators': 374}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:10:17,660] Trial 66 finished with value: 0.7127344896442634 and parameters: {'bootstrap': 'True', 'max_depth': 4320, 'max_features': 'sqrt', 'max_leaf_nodes': 6031, 'n_estimators': 307}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:10:29,519] Trial 67 finished with value: 0.6961747432814231 and parameters: {'bootstrap': 'True', 'max_depth': 3563, 'max_features': 'sqrt', 'max_leaf_nodes': 6268, 'n_estimators': 777}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:10:32,779] Trial 68 finished with value: 0.7053093316834588 and parameters: {'bootstrap': 'True', 'max_depth': 7761, 'max_features': 'sqrt', 'max_leaf_nodes': 5224, 'n_estimators': 214}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:10:35,691] Trial 69 finished with value: 0.6974785430331322 and parameters: {'bootstrap': 'False', 'max_depth': 8296, 'max_features': 'sqrt', 'max_leaf_nodes': 6880, 'n_estimators': 157}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:10:42,117] Trial 70 finished with value: 0.7132130432924517 and parameters: {'bootstrap': 'True', 'max_depth': 6340, 'max_features': 'sqrt', 'max_leaf_nodes': 5989, 'n_estimators': 342}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:10:46,925] Trial 71 finished with value: 0.7036673834317239 and parameters: {'bootstrap': 'True', 'max_depth': 6246, 'max_features': 'sqrt', 'max_leaf_nodes': 5745, 'n_estimators': 315}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:10:52,164] Trial 72 finished with value: 0.7004990811611285 and parameters: {'bootstrap': 'True', 'max_depth': 5626, 'max_features': 'sqrt', 'max_leaf_nodes': 6887, 'n_estimators': 358}. Best is trial 29 with value: 0.7168913179479336.
[I 2022-05-29 14:10:57,080] Trial 73 finished with value: 0.7060524653508059 and parameters: {'bootstrap': 'True', 'max_depth': 4872, 'max_features': 'sqrt', 'max_leaf_nodes': 6217, 'n_estimators': 264}. Best is trial 29 with value: 0.7168913179479336.

In [ ]:
fig = optuna.visualization.plot_param_importances(study)
fig.show()

In [28]:
def detailed_objective(trial):
    # Use same code objective to reproduce the best model
    X, y = make_classification(n_features=10, random_state=1)
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
    C = trial.suggest_loguniform("C", 1e-7, 10.0)
    clf = LogisticRegression(C=C)
    clf.fit(X_train, y_train)
    # calculate more evaluation metrics
    pred = clf.predict(X_test)
    acc = metrics.accuracy_score(pred, y_test)
    recall = metrics.recall_score(pred, y_test)
    precision = metrics.precision_score(pred, y_test)
    f1 = metrics.f1_score(pred, y_test)
    return acc, f1, recall, precision

In [29]:
X=ibex_df4.copy()
X.dropna(axis=0,inplace= True)
y=X.Target
X.reset_index(inplace=True)
X.drop('Target',axis=1, inplace=True)
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.3,
                                                    random_state=42
                                                    )

NameError: name 'ibex_df4' is not defined

In [342]:
param_test1 = {'n_estimators':range(20,300,10)}
gsearch1 = GridSearchCV(estimator = ExtraTreesClassifier(),
                        param_grid = param_test1, 
                        n_jobs = 4, 
                        cv = 5,
                        verbose = 4,
)

gsearch1.fit(X_train,y_train)

Fitting 5 folds for each of 28 candidates, totalling 140 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  17 tasks      | elapsed:    9.2s
[Parallel(n_jobs=4)]: Done  90 tasks      | elapsed:   45.5s
[Parallel(n_jobs=4)]: Done 140 out of 140 | elapsed:  1.6min finished

GridSearchCV(cv=5, error_score=nan,
             estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0,
                                            class_weight=None, criterion='gini',
                                            max_depth=None, max_features='auto',
                                            max_leaf_nodes=None,
                                            max_samples=None,
                                            min_impurity_decrease=0.0,
                                            min_impurity_split=None,
                                            min_samples_leaf=1,
                                            min_samples_split=2,
                                            min_weight_fraction_leaf=0.0,
                                            n_estimators=100, n_jobs=None,
                                            oob_score=False, random_state=None,
                                            verbose=0, warm_start=False),
             iid='deprecated', n_jobs=4,
             param_grid={'n_estimators': range(20, 300, 10)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=4)

In [343]:
gsearch1.best_params_, gsearch1.best_score_

({'n_estimators': 240}, 0.689068136145903)

In [351]:
scoring_f1(y_test,X_test,gsearch1)

0.7137069661061817

In [345]:
param_test2 = {'n_estimators':[240], 'criterion': ['gini', 'entropy', 'log_loss']}
gsearch2 = GridSearchCV(estimator = ExtraTreesClassifier(),
                        param_grid = param_test2, 
                        n_jobs = 4, 
                        cv = 5,
                        verbose = 4,
)

gsearch2.fit(X_train,y_train)

Fitting 5 folds for each of 3 candidates, totalling 15 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  12 out of  15 | elapsed:   16.7s remaining:    4.1s
[Parallel(n_jobs=4)]: Done  15 out of  15 | elapsed:   18.9s finished

GridSearchCV(cv=5, error_score=nan,
             estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0,
                                            class_weight=None, criterion='gini',
                                            max_depth=None, max_features='auto',
                                            max_leaf_nodes=None,
                                            max_samples=None,
                                            min_impurity_decrease=0.0,
                                            min_impurity_split=None,
                                            min_samples_leaf=1,
                                            min_samples_split=2,
                                            min_weight_fraction_leaf=0.0,
                                            n_estimators=100, n_jobs=None,
                                            oob_score=False, random_state=None,
                                            verbose=0, warm_start=False),
             iid='deprecated', n_jobs=4,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'n_estimators': [240]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=4)

In [346]:
gsearch2.best_params_, gsearch2.best_score_

({'criterion': 'entropy', 'n_estimators': 240}, 0.6879447934176766)

In [350]:
scoring_f1(y_test,X_test,gsearch2)

0.7126813595129133

In [352]:
param_test3 = {'n_estimators':[240], 'criterion': ['entropy']}
gsearch3 = GridSearchCV(estimator = ExtraTreesClassifier(),
                        param_grid = param_test3, 
                        n_jobs = 4, 
                        cv = 5,
                        verbose = 4,
)

gsearch3.fit(X_train,y_train)

Fitting 5 folds for each of 1 candidates, totalling 5 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   2 out of   5 | elapsed:   10.7s remaining:   16.1s
[Parallel(n_jobs=4)]: Done   5 out of   5 | elapsed:   13.7s finished

GridSearchCV(cv=5, error_score=nan,
             estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0,
                                            class_weight=None, criterion='gini',
                                            max_depth=None, max_features='auto',
                                            max_leaf_nodes=None,
                                            max_samples=None,
                                            min_impurity_decrease=0.0,
                                            min_impurity_split=None,
                                            min_samples_leaf=1,
                                            min_samples_split=2,
                                            min_weight_fraction_leaf=0.0,
                                            n_estimators=100, n_jobs=None,
                                            oob_score=False, random_state=None,
                                            verbose=0, warm_start=False),
             iid='deprecated', n_jobs=4,
             param_grid={'criterion': ['entropy'], 'n_estimators': [240]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=4)

## test_X prediction

To take advantage of all the dataset, the model with the best hyperparameters is fitted with the whole train data:

In [362]:
best_final_model = ExtraTreesClassifier(class_weight=None, 
                                  criterion='entropy',
                                max_depth=None, 
                                max_features='auto',
                                max_leaf_nodes=None,
                                max_samples=None,
                                min_impurity_decrease=0.0,
                                min_impurity_split=None,
                                min_samples_leaf=1,
                                min_samples_split=2,
                                min_weight_fraction_leaf=0.0,
                                n_estimators=240, 
                                n_jobs=5,
                                random_state=None,
                                )

In [369]:
X.drop('index', axis=1,inplace=True)

In [370]:
best_final_model.fit(X,y)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='entropy', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=240, n_jobs=5,
                     oob_score=False, random_state=None, verbose=0,
                     warm_start=False)

Charge test_X dataset to be predicted. First of all, additional columns have to be generated as the most useful dataframe (ibex_df4):

In [371]:
test_x=pd.read_csv('C:/Users/march/000 Treball Ju`yter 000/Hackathons/Tech_laCaixa2022/test_x.csv',index_col=None)

test_x.isnull().sum()

test_index    0
Date          0
Open          0
High          0
Low           0
Close         0
Adj Close     0
Volume        0
dtype: int64

In [372]:
test_x.shape

(726, 8)

In [373]:

test_x

,test_index,Date,Open,High,Low,Close,Adj Close,Volume
0,6557,2019-06-05,9136.799805,9173.400391,9095.000000,9150.500000,9150.500000,158753000.0
1,6558,2019-06-06,9169.200195,9246.200195,9136.700195,9169.200195,9169.200195,212720900.0
2,6559,2019-06-07,9186.700195,9261.400391,9185.700195,9236.099609,9236.099609,150664700.0
3,6560,2019-06-10,9284.200195,9302.200195,9248.099609,9294.099609,9294.099609,102323700.0
4,6561,2019-06-11,9288.599609,9332.500000,9273.400391,9282.099609,9282.099609,144701200.0
...,...,...,...,...,...,...,...,...
721,7278,2022-03-25,8314.099609,8363.200195,8286.500000,8330.599609,8330.599609,156189000.0
722,7279,2022-03-28,8354.400391,8485.700195,8354.400391,8365.599609,8365.599609,167961800.0
723,7280,2022-03-29,8451.000000,8621.000000,8419.700195,8614.599609,8614.599609,257812200.0
724,7281,2022-03-30,8583.299805,8597.400391,8508.900391,8550.599609,8550.599609,185389000.0
725,7282,2022-03-31,8562.599609,8588.299805,8445.099609,8445.099609,8445.099609,220117500.0

In [374]:
test_x. rename(columns = {'test_index':'day'}, inplace = True)
test_x.drop('Date',axis=1,inplace=True)

test_x

,day,Open,High,Low,Close,Adj Close,Volume
0,6557,9136.799805,9173.400391,9095.000000,9150.500000,9150.500000,158753000.0
1,6558,9169.200195,9246.200195,9136.700195,9169.200195,9169.200195,212720900.0
2,6559,9186.700195,9261.400391,9185.700195,9236.099609,9236.099609,150664700.0
3,6560,9284.200195,9302.200195,9248.099609,9294.099609,9294.099609,102323700.0
4,6561,9288.599609,9332.500000,9273.400391,9282.099609,9282.099609,144701200.0
...,...,...,...,...,...,...,...
721,7278,8314.099609,8363.200195,8286.500000,8330.599609,8330.599609,156189000.0
722,7279,8354.400391,8485.700195,8354.400391,8365.599609,8365.599609,167961800.0
723,7280,8451.000000,8621.000000,8419.700195,8614.599609,8614.599609,257812200.0
724,7281,8583.299805,8597.400391,8508.900391,8550.599609,8550.599609,185389000.0
725,7282,8562.599609,8588.299805,8445.099609,8445.099609,8445.099609,220117500.0

In [376]:
index_new=list(test_x.day)

In [377]:
test_x.index=index_new
test_x

,day,Open,High,Low,Close,Adj Close,Volume,Oscillation,daily_variation,MA_200_dias,MA_20_dias,MA_5_dias,MA_3_dias,dist_Max_200_d,dist_Max_50_d,dist_Max_20_d,dist_Min_200_d,dist_Min_50_d,dist_Min_20_d
6557,6557,9136.799805,9173.400391,9095.000000,9150.500000,9150.500000,158753000.0,78.400391,13.700195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6558,6558,9169.200195,9246.200195,9136.700195,9169.200195,9169.200195,212720900.0,109.500000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6559,6559,9186.700195,9261.400391,9185.700195,9236.099609,9236.099609,150664700.0,75.700196,49.399414,NaN,NaN,NaN,9185.266601,NaN,NaN,NaN,NaN,NaN,NaN
6560,6560,9284.200195,9302.200195,9248.099609,9294.099609,9294.099609,102323700.0,54.100586,9.899414,NaN,NaN,NaN,9233.133138,NaN,NaN,NaN,NaN,NaN,NaN
6561,6561,9288.599609,9332.500000,9273.400391,9282.099609,9282.099609,144701200.0,59.099609,-6.500000,NaN,NaN,9226.399804,9270.766276,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7278,7278,8314.099609,8363.200195,8286.500000,8330.599609,8330.599609,156189000.0,76.700195,16.500000,8716.979521,8202.210010,8368.100000,8321.366536,-865.300782,-555.600586,-156.600586,685.999511,685.999511,685.999511
7279,7279,8354.400391,8485.700195,8354.400391,8365.599609,8365.599609,167961800.0,131.299804,11.199218,8712.828018,8196.529980,8363.379883,8333.766276,-817.000000,-520.600586,-121.600586,720.999511,720.999511,720.999511
7280,7280,8451.000000,8621.000000,8419.700195,8614.599609,8614.599609,257812200.0,201.299805,163.599609,8710.748018,8217.849951,8388.859765,8436.932942,-568.000000,-271.600586,0.000000,969.999511,969.999511,969.999511
7281,7281,8583.299805,8597.400391,8508.900391,8550.599609,8550.599609,185389000.0,88.500000,-32.700196,8708.242515,8229.329932,8433.299609,8510.266276,-632.000000,-335.600586,-64.000000,905.999511,905.999511,905.999511
7282,7282,8562.599609,8588.299805,8445.099609,8445.099609,8445.099609,220117500.0,143.200196,-117.500000,8705.201514,8251.014917,8461.299609,8536.766276,-737.500000,-441.100586,-169.500000,800.499511,800.499511,800.499511

To fill the nan values in the test_x, it can be concatenated to initial dataframe to calculate moving averages, distances to maximums an minimums:

In [401]:
predictions_df['test_index']=index_new
predictions_df.index= predictions_df['test_index']
predictions_df.drop('test_index',axis=1,inplace=True)
predictions_df

            Predictions
test_index
6557                  0
6558                  0
6559                  0
6560                  0
6561                  0
...                 ...
7278                  1
7279                  1
7280                  1
7281                  1
7282                  1

[726 rows x 1 columns]

In [402]:
#predictions_df.to_csv('C:/Users/march/000 Treball Ju`yter 000/Hackathons/Tech_laCaixa2022/predictions.csv')

In [403]:
#predictions_df.to_json('C:/Users/march/000 Treball Ju`yter 000/Hackathons/Tech_laCaixa2022/predictions.json')